TO-57 homepage-services
archis-academy/tour-and-travel-dec-2-tr pull request #1
Opened 2023-12-11 19:17 UTC by engindenizz

TO-57 homepage-services

2023-12-13 12:21 UTC, alperenustun requested changes
- [x] class isimleri daha spesifik olmalı
- [x] prettier kullanarak kod formatlaması yapmalısın
- [ ] yazı renkleri figmadaki ile aynı olsun ( ya da diğer bütün renkler)

2023-12-13 21:19 UTC, engindenizz commented
fixed

2023-12-16 09:48 UTC, mehmetkumruu approved these changes

2023-12-16 09:48 UTC, mehmetkumruu commented on styles/shared.css
> +  font-family: "Poppins", sans-serif;
Body font family olmamalı eğer Bi element bütün bir sayfa da öyle ise element etiketi kullanmanı tavsiye ederim ve aslında ihtiyacın yok çünkü sadece 1 ticket çalışıyorsun mümkün olduğunca diğer arkadaşlarına yansımayacak kodları ve etiketleri kullan

2023-12-16 09:48 UTC, mehmetkumruu commented on styles/index.css
> +  height: 100px;
Width ve height i img elementinin kendisine uygulaman daha iyi olacaktır burda

2023-12-16 18:17 UTC, engindenizz commented on styles/shared.css
> +  font-family: "Poppins", sans-serif;
düzeltildi

2023-12-16 18:18 UTC, engindenizz commented on styles/index.css
> +  height: 100px;
hocam burda box oluşturmak için verdim width ve heightı

2023-12-22 18:12 UTC, alperenustun requested changes
- [ ] margin yerine gap daha iyi olur

2024-01-11 12:02 UTC, merged